apiVersion: v1
kind: Service
metadata:
  name: gym-app-service
spec:
  selector:
    app: gym-app
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000