apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gym-app
  labels:
    app: gym-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
      containers:
      - name: gym-app
        image: gym-app
        imagePullPolicy: Never
        ports: 
        - containerPort: 3000
        env:
        - name : username
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: password
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name : host
          valueFrom: 
            configMapKeyRef:
              name: mongo-configmap
              key: database_url
        - name: database-
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-database